# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4049e85bc7dcf6ed1b760f227e6bde8b9ce526c17fb9d13b3a6ce0b26a89930ae12ab50c24ac30066396d7a46df552acc6e428062a4e22bde05e6d2c9fa9b6

test:
  secret_key_base: 8fcbc8911779ab0c6a357f0ad97e0031538b54fa4d219572be4406bf0309b6861fbbdaab5e4f0fd177a8c8cb6b37674897271d5470920737a92c663e33409c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
